### ISSUE TITLE
Not displaying correctly on iPhone X

### ISSUE THREAD

**Issue by rlindsey2** [ShawnBaek/Custom-UIKit-NavigationBar#4]
The navigation bar doesn't seem to take into account the notch on the iPhone X. I've not adjusted any code and am wondered what the workaround is for this?

<img width="333" alt="screen shot 2018-03-30 at 18 35 56" src="https://user-images.githubusercontent.com/37937966/38147240-47bd2276-3449-11e8-8bcb-b8eaba07b595.png">

**Comment by ShawnBaek** [comment]
I just fixed the problem with iPhonex. Check it out and let me know if there are any problems. Thank you.

**Comment by SlavaBreath** [comment]
Xcode 9.4, Swift 4.1, iPhone X simulator iOS 11.4 still the same issue. The additional height is not taking into account
